apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # Jenkins will replace BUILD_TAG with the current build number before apply
        image: aa309m/myapp:BUILD_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
