
---
- name: Deploy myapp to Kubernetes cluster
  hosts: eks
  become: false
  tasks:
    - name: Apply Kubernetes deployment
      command: kubectl apply -f /home/ec2-user/deployment.yaml

    - name: Apply Kubernetes service
      command: kubectl apply -f /home/ec2-user/service.yaml

